version: "3"
services:
  folio-client:
    image: folio-client
    build: ./folio-client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - folio-network
    # volumes:
    #   - ./folio-client/:/usr/src/app
    #   - /usr/src/app/node_modules
    container_name: folio-client

  folio-server:
    image: folio-server
    build:
      context: ./folio-server/
      args:
        MONGODB_USER: admin
        MONGODB_PASSWORD: Admin123
    ports:
      - "5000:5000"
    networks:
      - folio-network
    # volumes:
    #   - ./folio-server/:/usr/src/app
    #   - /usr/src/app/node_modules
    depends_on:
      - mongo
    container_name: folio-server

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - folio-network
    # volumes:
    #   - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin123
    container_name: mongo

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:Admin123@mongo:27017/
    networks:
      - folio-network
    depends_on:
      - mongo
    container_name: mongo-express
networks:
  folio-network:
    driver: bridge
# volumes:
#   mongo-data:
#     driver: local
