# first stage

FROM node:18-slim

COPY . /usr/src/app

WORKDIR /usr/src/app

RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

RUN npm i

RUN npm build

# second stage

FROM caddy:2.5.1-alpine

ARG CADDYFILE

COPY ${CADDYFILE}  /etc/caddy/Caddyfile

