build:
	docker build -t folio-client:latest .

build-local:
	sudo docker build -t folio-client-local:latest -f Dockerfile.local .


build-production:
	sudo docker build -t folio-client-production:latest -f Dockerfile.production .